title: Tethered Lab
description: "Exploring the dialogue between human thought and machine reflection."
url: "https://tetheredlab.com"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: G-G2N0CX2XMQ
