title: Tethered Lab
description: "A living experiment in human-AI reflections."
url: "https://tetheredlab.com"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: G-G2N0CX2XMQ
